### ISSUE TITLE
file view breadcrumbs has a trailing / on files

### ISSUE THREAD

**Issue by isovector** [isovector/take2#32]

**Comment by scarg0e** [comment]
As it stands, the href tag on the breadcrumbs element is a bit redundant. Clicking it will simply take you to the file you are currently on (refreshes the page).

Do we want to make each part of the breadcrumbs link to it's corresponding folder?
ie. /folder1/folder2/document
where clicking folder1 takes you to folder 1, folder 2 takes you to folder 2, etc.
@adobrik

**Comment by scarg0e** [comment]
Looks like this is only an issue when running the server locally on a windows machine ('/' vs '\' issue).

**Comment by ja6lee** [comment]
Slashes got broken on linux / Mac, now fixed.
