### ISSUE TITLE
cant start server

### ISSUE THREAD

**Issue by MatthewMaclean** [isovector/take2#41]
![11028082_10153176576494617_2004678634_o](https://cloud.githubusercontent.com/assets/1004435/6519897/ab826800-c388-11e4-9815-35559c8fc669.jpg)

**Comment by isovector** [comment]
learn to copy+paste :-1:

**Comment by isovector** [comment]
try inserting 

```scala
Logger.info(file)
```
above this line:
```scala
val repoFile = RepoFile.getByFile(file).get
```

then crossreference that against the database:

```sql
select * from RepoFile where file = 'whateveryougotabove';
```

does it exist? if not, does ANYTHING?
```sql
select * from RepoFile;
```

if nothing exists, does the COMMIT?
```sql
-- backticks are necessary here
select * from `Commit`; 
```

if nothing exists, database is fucky. if the repofile exists, something's going wrong with matt's parsing stuff probably. if things exist but the repofile doesn't, then check RepoFileModel#touchFiles and see if that's ever getting hit.

**Comment by isovector** [comment]
closing this due to no follow up

**Comment by MatthewMaclean** [comment]
I tried it twice, the first time it tried to find README.md, the second it tried to find back/app/controlelrs/Appliation.scala. Both exist in the database, but when it tries to get by file, it fails.

**Comment by isovector** [comment]
delete the db and try again

**Comment by isovector** [comment]
or ortherwise get me more useful information

**Comment by MatthewMaclean** [comment]
That was after deleting the db and restarting the server. I'll just not use my local machine I guess.

**Comment by isovector** [comment]
naw, this is definitely something we should fix

**Comment by isovector** [comment]
for the meantime actually i guess you can just early return from that function so the .get doesn't happen
