### ISSUE TITLE
FileView is parsing the actual file and trying to run it.

### ISSUE THREAD

**Issue by ja6lee** [isovector/take2#47]
On .html files we see a lot of errors, and sometime it stops the file from being shown at all. It looks like its actually making calls that are in the code.. and it shouldn't be.
![screen shot 2015-03-07 at 5 53 07 pm](https://cloud.githubusercontent.com/assets/1832516/6543659/d9c4e254-c4f2-11e4-8c8d-5a4fc2f6a5cf.png)
![screen shot 2015-03-07 at 5 52 39 pm](https://cloud.githubusercontent.com/assets/1832516/6543658/d9c45ac8-c4f2-11e4-9ab0-9962434b3e9c.png)

**Comment by isovector** [comment]
a probably easy fix for this is to use the backend to replace all < with &lt; and liekwise for >

**Comment by scarg0e** [comment]
fixed on the frontend with aforemention method #57
